use_frameworks!

platform :ios, '9.0'

target 'FCBaseOCKit_Example' do
  pod 'FCBaseOCKit', :path => '../'

  pod 'FCCollectionViewLayout/ObjC'

  target 'FCBaseOCKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
